import { StyleSheet } from 'react-native';
import { Palette } from '@/constants/theme';

export const styles = StyleSheet.create({
  contenedorPrincipal: {
    flex: 1,
    position: 'relative',
  },
  scroll: {
    flex: 1,
  },
  contenedorScroll: {
    padding: 16,
    paddingBottom: 110,
    gap: 16,
    maxWidth: 1440,
    alignSelf: 'center',
    width: '100%',
  },
  layoutDosColumnas: {
    flexDirection: 'row',
    gap: 20,
    alignItems: 'flex-start',
  },
  columnaIzquierda: {
    width: 500,
    maxWidth: '44%',
    gap: 16,
  },
  columnaDerecha: {
    flex: 1,
    minHeight: 680,
  },
  layoutMovil: {
    gap: 16,
  },
  tarjeta: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D0DEC8',
    padding: 16,
    gap: 14,
  },
  tarjetaMapaEscritorio: {
    minHeight: 700,
    flex: 1,
  },
  tituloSeccion: {
    fontSize: 15,
    fontWeight: '800',
    color: Palette.forestGreen,
  },
  cabeceraMapa: {
    gap: 4,
  },
  ayudaMapa: {
    fontSize: 12,
    color: '#6B7280',
  },
  filaDosColumnas: {
    flexDirection: 'row',
    gap: 12,
  },
  columna: {
    flex: 1,
  },
  barraAccionesFlotanteWrapper: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 8,
    alignItems: 'center',
    zIndex: 50,
  },
  barraAccionesCard: {
    width: '100%',
    maxWidth: 1440,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D0DEC8',
    paddingHorizontal: 20,
    paddingVertical: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  cabeceraSeccionTerritorial: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  badgeDetectando: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1B5E20',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#C8E6C9',
  },
  cajaNotificacionAuto: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#F1F8E9',
    borderColor: '#C5E1A5',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  textoNotificacionAuto: {
    fontSize: 12,
    color: '#33691E',
    fontWeight: '600',
    flex: 1,
  },
  cajaCoordenadasGps: {
    backgroundColor: '#F9FBF8',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DFEAE0',
    padding: 12,
    gap: 8,
  },
  cabeceraCoordenadas: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
  },
  filaTituloCoord: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tituloCoordenadas: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2E7D32',
  },
  badgeCentroide: {
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  textoBadgeCentroide: {
    fontSize: 10,
    fontWeight: '700',
    color: '#2E7D32',
  },
  filaCoordenadasValores: {
    flexDirection: 'row',
    gap: 12,
  },
  campoCoordenada: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  etiquetaCoordenada: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  valorCoordenada: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  textoCoordenadasPendiente: {
    fontSize: 11,
    color: '#6B7280',
    fontStyle: 'italic',
  },
});
